on:
  pull_request:

name: Suggestions

jobs:
  shell:
    name: Shell suggestions
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: install shellcheck
        run: |
          scversion="latest"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-${scversion}/shellcheck" /usr/local/bin/
          rm -rf "shellcheck-${scversion}/shellcheck"
          
      - run: shellcheck -x -f diff $(shfmt -f .) | patch -p1
      - run: docker run --rm -v "$PWD:/mnt" -w /mnt mvdan/shfmt:v3 -i 2 -ci -w .

      - name: suggester / shellcheck
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: shellcheck / shfmt

  markdownlint-prettier:
    name: markdownlint and prettier suggestions
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - run: sudo npm install -g markdownlint-cli
      - run: sudo npm install -g prettier

      - run: markdownlint --fix --ignore site/_includes . || true
      - run: prettier -u -w '**/*.yaml' '**/.*.yaml' '**/*.yml' '**/.*.yml' '**/*.json' '**/*.md' || true

      - name: suggester / prettier
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: markdownlint / prettier

  black:
    name: Black formatter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: suggester / black
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: black
